<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('students', function (Blueprint $table) {
            // Enrolment lifecycle: provisional until confirmed (first payment OR registrar action)
            $table->string('enrolment_status')->default('provisional')->after('status');
            // provisional | confirmed
            $table->timestamp('confirmed_at')->nullable()->after('enrolment_status');
            $table->string('confirmed_via')->nullable()->after('confirmed_at');
            // 'payment' | 'manual' — records which trigger fired first

            // National identifiers — stored, never generated by this system.
            // LIN = Learner Identification Number (EMIS/UNEB). NIN = National ID.
            // Nullable: a new S1 student is often admitted before their LIN arrives.
            $table->string('lin')->nullable()->after('admission_no');
            $table->string('nin')->nullable()->after('lin');

            $table->index(['school_id', 'enrolment_status']);
        });
    }

    public function down(): void
    {
        Schema::table('students', function (Blueprint $table) {
            $table->dropIndex(['school_id', 'enrolment_status']);
            $table->dropColumn(['enrolment_status', 'confirmed_at', 'confirmed_via', 'lin', 'nin']);
        });
    }
};
